# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/MS770/setup-makefiles.sh


# -------------------------------------------------------------------
# PREBUILT LIBRARIES THAT ARE NEEDED TO BUILD OPEN-SOURCE LIBRARIES -
# -------------------------------------------------------------------
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
######################    DEPENDENCY SECTION  #######################
PRODUCT_COPY_FILES += \
    vendor/lge/MS770/proprietary/system/lib/libacdbloader.so:obj/lib/libacdbloader.so \
    vendor/lge/MS770/proprietary/system/lib/libcamera_client.so:obj/lib/libcamera_client.so \
    vendor/lge/MS770/proprietary/system/lib/libmmipl.so:obj/lib/libmmipl.so \
    vendor/lge/MS770/proprietary/system/lib/libmmjpeg.so:obj/lib/libmmjpeg.so \
    vendor/lge/MS770/proprietary/system/lib/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/lge/MS770/proprietary/system/lib/libril.so:obj/lib/libril.so


#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
###################### DON'T EDIT ###################################
PRODUCT_COPY_FILES += \
    vendor/lge/MS770/proprietary/system/bin/atd:system/bin/atd \
    vendor/lge/MS770/proprietary/system/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/lge/MS770/proprietary/system/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/lge/MS770/proprietary/system/bin/btnvtool:system/bin/btnvtool \
    vendor/lge/MS770/proprietary/system/bin/cnd:system/bin/cnd \
    vendor/lge/MS770/proprietary/system/bin/drmdiagapp:system/bin/drmdiagapp \
    vendor/lge/MS770/proprietary/system/bin/drmserver:system/bin/drmserver \
    vendor/lge/MS770/proprietary/system/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/lge/MS770/proprietary/system/bin/ftm_ptt:system/bin/ftm_ptt \
    vendor/lge/MS770/proprietary/system/bin/gsiff_daemon:system/bin/gsiff_daemon \
    vendor/lge/MS770/proprietary/system/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/lge/MS770/proprietary/system/bin/hdmid:system/bin/hdmid \
    vendor/lge/MS770/proprietary/system/bin/hostapd:system/bin/hostapd \
    vendor/lge/MS770/proprietary/system/bin/lgdrmserver:system/bin/lgdrmserver \
    vendor/lge/MS770/proprietary/system/bin/lgsecclkserver:system/bin/lgsecclkserver \
    vendor/lge/MS770/proprietary/system/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/lge/MS770/proprietary/system/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/lge/MS770/proprietary/system/bin/mpdecision:system/bin/mpdecision \
    vendor/lge/MS770/proprietary/system/bin/mtsd:system/bin/mtsd \
    vendor/lge/MS770/proprietary/system/bin/netmgrd:system/bin/netmgrd \
    vendor/lge/MS770/proprietary/system/bin/port-bridge:system/bin/port-bridge \
    vendor/lge/MS770/proprietary/system/bin/profiler_daemon:system/bin/profiler_daemon \
    vendor/lge/MS770/proprietary/system/bin/qmiproxy:system/bin/qmiproxy \
    vendor/lge/MS770/proprietary/system/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/MS770/proprietary/system/bin/qseecomd:system/bin/qseecomd \
    vendor/lge/MS770/proprietary/system/bin/quipc_igsn:system/bin/quipc_igsn \
    vendor/lge/MS770/proprietary/system/bin/quipc_main:system/bin/quipc_main \
    vendor/lge/MS770/proprietary/system/bin/rild:system/bin/rild \
    vendor/lge/MS770/proprietary/system/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/MS770/proprietary/system/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/lge/MS770/proprietary/system/bin/smpl_count:system/bin/smpl_count \
    vendor/lge/MS770/proprietary/system/bin/thermald:system/bin/thermald \
    vendor/lge/MS770/proprietary/system/bin/time_daemon:system/bin/time_daemon \
    vendor/lge/MS770/proprietary/system/bin/usbhub_init:system/bin/usbhub_init \
    vendor/lge/MS770/proprietary/system/bin/wiperiface:system/bin/wiperiface \
    vendor/lge/MS770/proprietary/system/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/lge/MS770/proprietary/system/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/lge/MS770/proprietary/system/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/lge/MS770/proprietary/system/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/lge/MS770/proprietary/system/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/lge/MS770/proprietary/system/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/lge/MS770/proprietary/system/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
    vendor/lge/MS770/proprietary/system/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/lge/MS770/proprietary/system/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/lge/MS770/proprietary/system/lib/hw/lights.msm8960.so:system/lib/hw/lights.msm8960.so \
    vendor/lge/MS770/proprietary/system/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/lge/MS770/proprietary/system/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx111_default_video.so:system/lib/libchromatix_imx111_default_video.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx111_preview.so:system/lib/libchromatix_imx111_preview.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx111_zsl.so:system/lib/libchromatix_imx111_zsl.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx119_default_video.so:system/lib/libchromatix_imx119_default_video.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx119_preview.so:system/lib/libchromatix_imx119_preview.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_imx119_vt.so:system/lib/libchromatix_imx119_vt.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/lge/MS770/proprietary/system/lib/libchromatix_s5k4e1_zsl.so:system/lib/libchromatix_s5k4e1_zsl.so \
    vendor/lge/MS770/proprietary/system/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/lge/MS770/proprietary/system/lib/libgemini.so:system/lib/libgemini.so \
    vendor/lge/MS770/proprietary/system/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/lge/MS770/proprietary/system/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/lge/MS770/proprietary/system/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
    vendor/lge/MS770/proprietary/system/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/lge/MS770/proprietary/system/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/lge/MS770/proprietary/system/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/lge/MS770/proprietary/system/lib/libOlaFaceDetector.so:system/lib/libOlaFaceDetector.so \
    vendor/lge/MS770/proprietary/system/lib/libOlaLGECameraJNI.so:system/lib/libOlaLGECameraJNI.so \
    vendor/lge/MS770/proprietary/system/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/lge/MS770/proprietary/system/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/lge/MS770/proprietary/system/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/lge/MS770/proprietary/system/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/lge/MS770/proprietary/system/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/lge/MS770/proprietary/system/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/lge/MS770/proprietary/system/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/lge/MS770/proprietary/system/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    vendor/lge/MS770/proprietary/system/lib/libgps.so:system/lib/libgps.so \
    vendor/lge/MS770/proprietary/system/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/lge/MS770/proprietary/system/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/lge/MS770/proprietary/system/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/lge/MS770/proprietary/system/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/lge/MS770/proprietary/system/lib/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/lge/MS770/proprietary/system/lib/libgsl.so:system/lib/libgsl.so \
    vendor/lge/MS770/proprietary/system/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/lge/MS770/proprietary/system/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/lge/MS770/proprietary/system/lib/libdiag.so:system/lib/libdiag.so \
    vendor/lge/MS770/proprietary/system/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/lge/MS770/proprietary/system/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/lge/MS770/proprietary/system/lib/libidl.so:system/lib/libidl.so \
    vendor/lge/MS770/proprietary/system/lib/libqdi.so:system/lib/libqdi.so \
    vendor/lge/MS770/proprietary/system/lib/libqdp.so:system/lib/libqdp.so \
    vendor/lge/MS770/proprietary/system/lib/libqmi.so:system/lib/libqmi.so \
    vendor/lge/MS770/proprietary/system/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/lge/MS770/proprietary/system/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/lge/MS770/proprietary/system/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/lge/MS770/proprietary/system/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/lge/MS770/proprietary/system/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/lge/MS770/proprietary/system/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/lge/MS770/proprietary/system/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/lge/MS770/proprietary/system/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/lge/MS770/proprietary/system/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/lge/MS770/proprietary/system/lib/libril.so:system/lib/libril.so \
    vendor/lge/MS770/proprietary/system/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/lge/MS770/proprietary/system/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/lge/MS770/proprietary/system/lib/liblgftmitem.so:system/lib/liblgftmitem.so

